### ISSUE TITLE
Very nice , little suggestion here

### ISSUE THREAD

**Issue by Luc4z** [TheZ3ro/pkmngo-map#12]
can we increase searching range ? and renew frequently -50% time to make it renew ealier, or just give a option for it , thanks man ! good job

**Comment by minthat** [comment]
You can increase the step range manually by editing main.py. We may add the ability to change it manually later, but for now just edit the step count in main.py.

Thay being said, no the scanning frequency cannot be improved atm, and increasing the step count will make it scan SLOWER.

**Comment by Luc4z** [comment]
appreciated for the answer , and how about a renew button for Pokemons just like Gym/Pokestopi ?

i got it now , thanks man , and i compared 3 map tools and this one scanning pokemons is the best , like missed less than the others , but just range is quite small but if we can set it ourself in floder then it would be fine , like if i want to increase dectect range i just need to raise step counte right ? 

thanks !

**Comment by minthat** [comment]
Yea, this repo will end up being the best all around, because the idea is to add every good feature that the rest of the repos have added + extra development from Z3ro and (sorta) myself.

We will almost definitely add customizable step distance in the near future.

For now, just go to line 68 of main.py (https://github.com/TheZ3ro/pkmngo-map/blob/maps/main.py) and change the value to your preferred choice.
