### ISSUE TITLE
Multi-User login?

### ISSUE THREAD

**Issue by scarecr0w12** [TheZ3ro/pkmngo-map#13]
Suggestion.

Would it difficult to add a system to this front end to allow for a player to mark a Location, and login using their creds for trainer/Google auth? If the refresh time was lowered down and a cache was made so it didn't need to load every X minutes, would limit the ban chance i would think.

**Comment by TheZ3ro** [comment]
Using your real credential is a risk.

Right now Niantic have an auto-ban of 5 minute to 3 hours if the player "moves" too fast.

**Comment by scarecr0w12** [comment]
Thats why i was thinking was lower the time is request the API. What im thinking is set it up like this:

-Player loads system
-Player puts in login creds & marks a point on map
-Map loads surrounding area based on mark location

Set is so you can only change placement markers ever X minutes. The only problem i see already is the fact its limited to a single login, single location. If that can be expanded, possibly integrating a DB like MySQL or somthing, would be perfect. (I run Pokeforums.com so would love to have this kind of system)

**Comment by TheZ3ro** [comment]
For the first part of your post, it will be possible as soon as we will implement the Heroku deploy.
So an user (with a PTC account) will be able to set up a "private" Internet web site.
This system will be single-user.


I don't have plan to develop a complex system to allow multi-user location because:
- Every user will need to login with his PTC account otherwise the system will need a lot of bot PTC account
- This will be extremely hard to scale (see Niantic servers) and to develop
- This system will be against Niantic Terms of Service for PokemonGo and maintain such a website/server is a risk for the SysAdmin. (Code instead can't be taken offline)
 
(Sorry, don't blame it on me)

**Comment by minthat** [comment]
Yea, adding the ability for multiple users to login at the same time isn't really on the list of things that need doing.  This feature enables only users who want to profit from others work to do so, by putting the whole thing behind a paywall.  That's not what we're here to do, so we won't.

As Z3ro said, eventually we'll implement the 1-click Heroku deploy for users who want to host their own map, but lack the knowledge to do so.  Honestly, I'm more of the mindset that it's better to just show those users over to one of the community maps that are being developed rather than make it easy for a whole bunch of people to break Niantic TOS and make it more likely that everything gets shut down.

If you would like to host it yourself now, it's pretty easy.  You can either host it on your local PC and open up port 8000 traffic on your router to that PC (bad idea, both for security and ban-ability) or you can launch a VM on Azure, Google Cloud, AWS, Digital Ocean, etc and run it all on there (better idea).  I currently run a VM in Azure for that very purpose.

**Comment by scarecr0w12** [comment]
Hmm, Thats understandable. Not actually looking to "Profit" from it, just provide our Website users a better map then what we currently provide which is a user generated one. If my idea is not a possibility, is there any chance to be able to port the data it pulls into a MySQL DB to maintain what it pulls?

**Comment by minthat** [comment]
I totally understand the intention, and it's totally possible too!  just check out reddit.com/r/pokemongodev for all the different tools and maps that are out there.  There are even a couple that allow multiple logins already!  Also there, are a couple projects with the idea of maintaining a database of spawn points in mind as well!  Unfortunately, they aren't very far yet, but you should definitely go and help them out!

Another (terrible atm) resource for spawn points is TheSilphRoad.com

**Comment by TheZ3ro** [comment]
Can I close this? Maybe as "won't fix"?
